//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Конвер фай.
    /// </summary>
    // *** Start programmer edit section *** (КонверФай CustomAttributes)

    // *** End programmer edit section *** (КонверФай CustomAttributes)
    [AutoAltered()]
    [Caption("Конвертированные файлы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонверФайE", new string[] {
            "ВыгрДок as \'Выгрузка документа\'",
            "ВыгрДок.Конвертация.ЗагрФайла.ЭксФайлы.Имя as \'Старое имя\'",
            "ВыгрДок.Конвертация.ИмяДок as \'Имя документа\'",
            "ВыгрДок.NewName as \'Новое имя файла\'",
            "ПутьФайла as \'Путь до файла\'"}, Hidden=new string[] {
            "ВыгрДок.NewName"})]
    [MasterViewDefineAttribute("КонверФайE", "ВыгрДок", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "NewName")]
    [View("КонверФайL", new string[] {
            "ВыгрДок.NewName as \'Новое имя файла\'",
            "ВыгрДок.Конвертация.ИмяДок as \'Имя документа\'",
            "ВыгрДок.Конвертация.ЗагрФайла.ЭксФайлы.Имя as \'Старое имя\'",
            "ПутьФайла as \'Путь до файла\'"})]
    public class КонверФай : ICSSoft.STORMNET.DataObject
    {
        
        private string fПутьФайла;
        
        private IIS.Kurs3.ВыгрДок fВыгрДок;
        
        // *** Start programmer edit section *** (КонверФай CustomMembers)

        // *** End programmer edit section *** (КонверФай CustomMembers)

        
        /// <summary>
        /// ПутьФайла.
        /// </summary>
        // *** Start programmer edit section *** (КонверФай.ПутьФайла CustomAttributes)

        // *** End programmer edit section *** (КонверФай.ПутьФайла CustomAttributes)
        [StrLen(255)]
        public virtual string ПутьФайла
        {
            get
            {
                // *** Start programmer edit section *** (КонверФай.ПутьФайла Get start)

                // *** End programmer edit section *** (КонверФай.ПутьФайла Get start)
                string result = this.fПутьФайла;
                // *** Start programmer edit section *** (КонверФай.ПутьФайла Get end)

                // *** End programmer edit section *** (КонверФай.ПутьФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КонверФай.ПутьФайла Set start)

                // *** End programmer edit section *** (КонверФай.ПутьФайла Set start)
                this.fПутьФайла = value;
                // *** Start programmer edit section *** (КонверФай.ПутьФайла Set end)

                // *** End programmer edit section *** (КонверФай.ПутьФайла Set end)
            }
        }
        
        /// <summary>
        /// Конвер фай.
        /// </summary>
        // *** Start programmer edit section *** (КонверФай.ВыгрДок CustomAttributes)

        // *** End programmer edit section *** (КонверФай.ВыгрДок CustomAttributes)
        [PropertyStorage(new string[] {
                "ВыгрДок"})]
        [NotNull()]
        public virtual IIS.Kurs3.ВыгрДок ВыгрДок
        {
            get
            {
                // *** Start programmer edit section *** (КонверФай.ВыгрДок Get start)

                // *** End programmer edit section *** (КонверФай.ВыгрДок Get start)
                IIS.Kurs3.ВыгрДок result = this.fВыгрДок;
                // *** Start programmer edit section *** (КонверФай.ВыгрДок Get end)

                // *** End programmer edit section *** (КонверФай.ВыгрДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КонверФай.ВыгрДок Set start)

                // *** End programmer edit section *** (КонверФай.ВыгрДок Set start)
                this.fВыгрДок = value;
                // *** Start programmer edit section *** (КонверФай.ВыгрДок Set end)

                // *** End programmer edit section *** (КонверФай.ВыгрДок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонверФайE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонверФайE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонверФайE", typeof(IIS.Kurs3.КонверФай));
                }
            }
            
            /// <summary>
            /// "КонверФайL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонверФайL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонверФайL", typeof(IIS.Kurs3.КонверФай));
                }
            }
        }
    }
}
