//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч загр.
    /// </summary>
    // *** Start programmer edit section *** (ТчЗагр CustomAttributes)

    // *** End programmer edit section *** (ТчЗагр CustomAttributes)
    [AutoAltered()]
    [Caption("Атрибуты загружаемого файла")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчЗагрE", new string[] {
            "Атрибут as \'Атрибут\'",
            "ТипАтр as \'Тип атрибута\'",
            "Ограничение as \'Ограничение\'",
            "Обязательное as \'Обязательное\'"})]
    public class ТчЗагр : ICSSoft.STORMNET.DataObject
    {
        
        private string fАтрибут;
        
        private IIS.Kurs3.ТипАтр fТипАтр;
        
        private int fОграничение;
        
        private bool fОбязательное;
        
        private IIS.Kurs3.ЗагрФайла fЗагрФайла;
        
        // *** Start programmer edit section *** (ТчЗагр CustomMembers)

        // *** End programmer edit section *** (ТчЗагр CustomMembers)

        
        /// <summary>
        /// Атрибут.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗагр.Атрибут CustomAttributes)

        // *** End programmer edit section *** (ТчЗагр.Атрибут CustomAttributes)
        [StrLen(255)]
        public virtual string Атрибут
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗагр.Атрибут Get start)

                // *** End programmer edit section *** (ТчЗагр.Атрибут Get start)
                string result = this.fАтрибут;
                // *** Start programmer edit section *** (ТчЗагр.Атрибут Get end)

                // *** End programmer edit section *** (ТчЗагр.Атрибут Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗагр.Атрибут Set start)

                // *** End programmer edit section *** (ТчЗагр.Атрибут Set start)
                this.fАтрибут = value;
                // *** Start programmer edit section *** (ТчЗагр.Атрибут Set end)

                // *** End programmer edit section *** (ТчЗагр.Атрибут Set end)
            }
        }
        
        /// <summary>
        /// Обязательное.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗагр.Обязательное CustomAttributes)

        // *** End programmer edit section *** (ТчЗагр.Обязательное CustomAttributes)
        public virtual bool Обязательное
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗагр.Обязательное Get start)

                // *** End programmer edit section *** (ТчЗагр.Обязательное Get start)
                bool result = this.fОбязательное;
                // *** Start programmer edit section *** (ТчЗагр.Обязательное Get end)

                // *** End programmer edit section *** (ТчЗагр.Обязательное Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗагр.Обязательное Set start)

                // *** End programmer edit section *** (ТчЗагр.Обязательное Set start)
                this.fОбязательное = value;
                // *** Start programmer edit section *** (ТчЗагр.Обязательное Set end)

                // *** End programmer edit section *** (ТчЗагр.Обязательное Set end)
            }
        }
        
        /// <summary>
        /// Ограничение.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗагр.Ограничение CustomAttributes)

        // *** End programmer edit section *** (ТчЗагр.Ограничение CustomAttributes)
        public virtual int Ограничение
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗагр.Ограничение Get start)

                // *** End programmer edit section *** (ТчЗагр.Ограничение Get start)
                int result = this.fОграничение;
                // *** Start programmer edit section *** (ТчЗагр.Ограничение Get end)

                // *** End programmer edit section *** (ТчЗагр.Ограничение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗагр.Ограничение Set start)

                // *** End programmer edit section *** (ТчЗагр.Ограничение Set start)
                this.fОграничение = value;
                // *** Start programmer edit section *** (ТчЗагр.Ограничение Set end)

                // *** End programmer edit section *** (ТчЗагр.Ограничение Set end)
            }
        }
        
        /// <summary>
        /// ТипАтр.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗагр.ТипАтр CustomAttributes)

        // *** End programmer edit section *** (ТчЗагр.ТипАтр CustomAttributes)
        public virtual IIS.Kurs3.ТипАтр ТипАтр
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗагр.ТипАтр Get start)

                // *** End programmer edit section *** (ТчЗагр.ТипАтр Get start)
                IIS.Kurs3.ТипАтр result = this.fТипАтр;
                // *** Start programmer edit section *** (ТчЗагр.ТипАтр Get end)

                // *** End programmer edit section *** (ТчЗагр.ТипАтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗагр.ТипАтр Set start)

                // *** End programmer edit section *** (ТчЗагр.ТипАтр Set start)
                this.fТипАтр = value;
                // *** Start programmer edit section *** (ТчЗагр.ТипАтр Set end)

                // *** End programmer edit section *** (ТчЗагр.ТипАтр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kurs3.ЗагрФайла.
        /// </summary>
        // *** Start programmer edit section *** (ТчЗагр.ЗагрФайла CustomAttributes)

        // *** End programmer edit section *** (ТчЗагр.ЗагрФайла CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗагрФайла"})]
        public virtual IIS.Kurs3.ЗагрФайла ЗагрФайла
        {
            get
            {
                // *** Start programmer edit section *** (ТчЗагр.ЗагрФайла Get start)

                // *** End programmer edit section *** (ТчЗагр.ЗагрФайла Get start)
                IIS.Kurs3.ЗагрФайла result = this.fЗагрФайла;
                // *** Start programmer edit section *** (ТчЗагр.ЗагрФайла Get end)

                // *** End programmer edit section *** (ТчЗагр.ЗагрФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчЗагр.ЗагрФайла Set start)

                // *** End programmer edit section *** (ТчЗагр.ЗагрФайла Set start)
                this.fЗагрФайла = value;
                // *** Start programmer edit section *** (ТчЗагр.ЗагрФайла Set end)

                // *** End programmer edit section *** (ТчЗагр.ЗагрФайла Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчЗагрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчЗагрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчЗагрE", typeof(IIS.Kurs3.ТчЗагр));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчЗагр.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчЗагр CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчЗагр CustomAttributes)
    public class DetailArrayOfТчЗагр : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kurs3.DetailArrayOfТчЗагр members)

        // *** End programmer edit section *** (IIS.Kurs3.DetailArrayOfТчЗагр members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчЗагр by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчЗагр.
        /// </summary>
        public DetailArrayOfТчЗагр(IIS.Kurs3.ЗагрФайла fЗагрФайла) : 
                base(typeof(ТчЗагр), ((ICSSoft.STORMNET.DataObject)(fЗагрФайла)))
        {
        }
        
        public IIS.Kurs3.ТчЗагр this[int index]
        {
            get
            {
                return ((IIS.Kurs3.ТчЗагр)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kurs3.ТчЗагр dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
