//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kurs3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч настр.
    /// </summary>
    // *** Start programmer edit section *** (ТчНастр CustomAttributes)

    // *** End programmer edit section *** (ТчНастр CustomAttributes)
    [AutoAltered()]
    [Caption("Атрибуты настройки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчНастрE", new string[] {
            "Атрибут as \'Атрибут\'",
            "ТипАтр as \'Тип атрибута\'",
            "Ограничение as \'Ограничение\'",
            "Обязательное as \'Обязательное\'"})]
    public class ТчНастр : ICSSoft.STORMNET.DataObject
    {
        
        private string fАтрибут;
        
        private bool fОбязательное;
        
        private IIS.Kurs3.ТипАтр fТипАтр;
        
        private int fОграничение;
        
        private IIS.Kurs3.НастрКонв fНастрКонв;
        
        // *** Start programmer edit section *** (ТчНастр CustomMembers)

        // *** End programmer edit section *** (ТчНастр CustomMembers)

        
        /// <summary>
        /// Атрибут.
        /// </summary>
        // *** Start programmer edit section *** (ТчНастр.Атрибут CustomAttributes)

        // *** End programmer edit section *** (ТчНастр.Атрибут CustomAttributes)
        [StrLen(255)]
        public virtual string Атрибут
        {
            get
            {
                // *** Start programmer edit section *** (ТчНастр.Атрибут Get start)

                // *** End programmer edit section *** (ТчНастр.Атрибут Get start)
                string result = this.fАтрибут;
                // *** Start programmer edit section *** (ТчНастр.Атрибут Get end)

                // *** End programmer edit section *** (ТчНастр.Атрибут Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчНастр.Атрибут Set start)

                // *** End programmer edit section *** (ТчНастр.Атрибут Set start)
                this.fАтрибут = value;
                // *** Start programmer edit section *** (ТчНастр.Атрибут Set end)

                // *** End programmer edit section *** (ТчНастр.Атрибут Set end)
            }
        }
        
        /// <summary>
        /// Обязательное.
        /// </summary>
        // *** Start programmer edit section *** (ТчНастр.Обязательное CustomAttributes)

        // *** End programmer edit section *** (ТчНастр.Обязательное CustomAttributes)
        public virtual bool Обязательное
        {
            get
            {
                // *** Start programmer edit section *** (ТчНастр.Обязательное Get start)

                // *** End programmer edit section *** (ТчНастр.Обязательное Get start)
                bool result = this.fОбязательное;
                // *** Start programmer edit section *** (ТчНастр.Обязательное Get end)

                // *** End programmer edit section *** (ТчНастр.Обязательное Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчНастр.Обязательное Set start)

                // *** End programmer edit section *** (ТчНастр.Обязательное Set start)
                this.fОбязательное = value;
                // *** Start programmer edit section *** (ТчНастр.Обязательное Set end)

                // *** End programmer edit section *** (ТчНастр.Обязательное Set end)
            }
        }
        
        /// <summary>
        /// Ограничение.
        /// </summary>
        // *** Start programmer edit section *** (ТчНастр.Ограничение CustomAttributes)

        // *** End programmer edit section *** (ТчНастр.Ограничение CustomAttributes)
        public virtual int Ограничение
        {
            get
            {
                // *** Start programmer edit section *** (ТчНастр.Ограничение Get start)

                // *** End programmer edit section *** (ТчНастр.Ограничение Get start)
                int result = this.fОграничение;
                // *** Start programmer edit section *** (ТчНастр.Ограничение Get end)

                // *** End programmer edit section *** (ТчНастр.Ограничение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчНастр.Ограничение Set start)

                // *** End programmer edit section *** (ТчНастр.Ограничение Set start)
                this.fОграничение = value;
                // *** Start programmer edit section *** (ТчНастр.Ограничение Set end)

                // *** End programmer edit section *** (ТчНастр.Ограничение Set end)
            }
        }
        
        /// <summary>
        /// ТипАтр.
        /// </summary>
        // *** Start programmer edit section *** (ТчНастр.ТипАтр CustomAttributes)

        // *** End programmer edit section *** (ТчНастр.ТипАтр CustomAttributes)
        public virtual IIS.Kurs3.ТипАтр ТипАтр
        {
            get
            {
                // *** Start programmer edit section *** (ТчНастр.ТипАтр Get start)

                // *** End programmer edit section *** (ТчНастр.ТипАтр Get start)
                IIS.Kurs3.ТипАтр result = this.fТипАтр;
                // *** Start programmer edit section *** (ТчНастр.ТипАтр Get end)

                // *** End programmer edit section *** (ТчНастр.ТипАтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчНастр.ТипАтр Set start)

                // *** End programmer edit section *** (ТчНастр.ТипАтр Set start)
                this.fТипАтр = value;
                // *** Start programmer edit section *** (ТчНастр.ТипАтр Set end)

                // *** End programmer edit section *** (ТчНастр.ТипАтр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kurs3.НастрКонв.
        /// </summary>
        // *** Start programmer edit section *** (ТчНастр.НастрКонв CustomAttributes)

        // *** End programmer edit section *** (ТчНастр.НастрКонв CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "НастрКонв"})]
        public virtual IIS.Kurs3.НастрКонв НастрКонв
        {
            get
            {
                // *** Start programmer edit section *** (ТчНастр.НастрКонв Get start)

                // *** End programmer edit section *** (ТчНастр.НастрКонв Get start)
                IIS.Kurs3.НастрКонв result = this.fНастрКонв;
                // *** Start programmer edit section *** (ТчНастр.НастрКонв Get end)

                // *** End programmer edit section *** (ТчНастр.НастрКонв Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчНастр.НастрКонв Set start)

                // *** End programmer edit section *** (ТчНастр.НастрКонв Set start)
                this.fНастрКонв = value;
                // *** Start programmer edit section *** (ТчНастр.НастрКонв Set end)

                // *** End programmer edit section *** (ТчНастр.НастрКонв Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчНастрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчНастрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчНастрE", typeof(IIS.Kurs3.ТчНастр));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчНастр.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчНастр CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчНастр CustomAttributes)
    public class DetailArrayOfТчНастр : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kurs3.DetailArrayOfТчНастр members)

        // *** End programmer edit section *** (IIS.Kurs3.DetailArrayOfТчНастр members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчНастр by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчНастр.
        /// </summary>
        public DetailArrayOfТчНастр(IIS.Kurs3.НастрКонв fНастрКонв) : 
                base(typeof(ТчНастр), ((ICSSoft.STORMNET.DataObject)(fНастрКонв)))
        {
        }
        
        public IIS.Kurs3.ТчНастр this[int index]
        {
            get
            {
                return ((IIS.Kurs3.ТчНастр)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kurs3.ТчНастр dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
